{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speckle-server-minion-api-objects
  namespace: {{ .Values.namespace }}
  labels:
{{ include "speckle.labels" . | indent 4 }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: speckle-alb
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/order: "1"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    {{- if .Values.cert_manager_issuer }}
    cert-manager.io/cluster-issuer: {{ .Values.cert_manager_issuer }}
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    {{- end }}
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP1
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/api/getobjects/"
        backend:
          service:
            name: speckle-server
            port:
              name: web
      - pathType: Prefix
        path: "/api/objects/"
        backend:
          service:
            name: speckle-server
            port:
              name: web
      - pathType: Prefix
        path: "/api/diff/"
        backend:
          service:
            name: speckle-server
            port:
              name: web
      - pathType: Prefix
        path: "/objects/"
        backend:
          service:
            name: speckle-server
            port:
              name: web
      - pathType: Prefix
        path: "/streams/"
        backend:
          service:
            name: speckle-server
            port:
              name: web
{{- end }}
